### ISSUE TITLE
Loss close to 0, acc nearly 1, but poor visual_feedbacks

### ISSUE THREAD

**Issue by hxk11111** [shahrukhqasim/TIES-2.0#22]
Hi Shahrukhqasim,

Thanks for sharing your project. I tried to train the model by tf-record downloaded from google drive you provided. Used the same tfrecord for train, val and test. 
For the training process, loss converged quickly, after 2000 iterations, I got the result as below:
Training Iteration 1999:
Accuracy - cells: 0.999771655 rows: 1 cols: 0.999677658
 Loss     - cells: 0.00083513 rows: 0.00029534733 cols: 0.00229700166
 Fraction - cells: 0.503221631 rows: 0.493117601 cols: 0.492601216
 Total loss: 0.00114249298

But when I checked the visual feedbacks, I got poor visualized result :
<img width="552" alt="屏幕快照 2019-10-30 上午11 03 38" src="https://user-images.githubusercontent.com/23485433/67825686-1d825600-fb05-11e9-9294-c2ebb8b263b1.png">
<img width="572" alt="屏幕快照 2019-10-30 上午11 03 54" src="https://user-images.githubusercontent.com/23485433/67825690-1f4c1980-fb05-11e9-8c93-bdb5fe7c44f6.png">

Does anybody have some advice or have similar problems? Many thanks

**Comment by hxk11111** [comment]
@shahrukhqasim

**Comment by phexic** [comment]
@hxk11111 In the author's code, only six samples were taken to show whether the results were correct.

**Comment by hungptit123** [comment]
HI @hxk11111 . I have problem while training. I don't know you see this.
Training Iteration 105:
Accuracy - cells: 0.978424609 rows: 0.895143926 cols: 0.803354 
 Loss     - cells: 0.0991929844 rows: 0.293497771 cols: 0.486667097 
 Fraction - cells: 0.0215753876 rows: 0.104856044 cols: 0.19664596 
 Total loss: 0.293119282
Training Iteration 106:
Accuracy - cells: 0.98035419 rows: 0.896977782 cols: 0.827894092 
 Loss     - cells: 0.0928051174 rows: 0.2944884 cols: 0.456886739 
 Fraction - cells: 0.0196458325 rows: 0.103022188 cols: 0.172105893 
 Total loss: 0.281393409
Training Iteration 107:
2019-12-02 11:23:50.896536: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[26,190] = [26, 109, 90] does not index into param shape [30,109,109,128]
Traceback (most recent call last):
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[26,190] = [26, 109, 90] does not index into param shape [30,109,109,128]
	 [[{{node conv_graph_dgcnn_fast_conv_1/GatherNd}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "table_adjacency_parsing.py", line 31, in <module>
    trainer.train()
  File "/home/hungdv/Documents/graphNN/TIES-verions2/python/iterators/table_adjacency_parsing_iterator.py", line 88, in train
    model.run_training_iteration(sess, summary_writer, iteration_number)
  File "/home/hungdv/Documents/graphNN/TIES-verions2/python/models/basic_model.py", line 400, in run_training_iteration
    ops_result = sess.run(ops_to_run, feed_dict = feed_dict)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[26,190] = [26, 109, 90] does not index into param shape [30,109,109,128]
	 [[node conv_graph_dgcnn_fast_conv_1/GatherNd (defined at /home/hungdv/Documents/graphNN/TIES-verions2/python/ops/ties.py:32) ]]

Errors may have originated from an input operation.
Input Source operations connected to node conv_graph_dgcnn_fast_conv_1/GatherNd:
 conv_graph_dgcnn_fast_conv_1/Cast (defined at /home/hungdv/Documents/graphNN/TIES-verions2/python/ops/ties.py:31)	
 conv_graph_dgcnn_fast_conv_1/conv2d_14/LeakyRelu (defined at /tmp/tmp8vnsy1dh.py:74)

Original stack trace for 'conv_graph_dgcnn_fast_conv_1/GatherNd':
  File "table_adjacency_parsing.py", line 31, in <module>
    trainer.train()
  File "/home/hungdv/Documents/graphNN/TIES-verions2/python/iterators/table_adjacency_parsing_iterator.py", line 53, in train
    model.initialize(training=True)
  File "/home/hungdv/Documents/graphNN/TIES-verions2/python/models/basic_model.py", line 94, in initialize
    self.build_computation_graphs()
  File "/home/hungdv/Documents/graphNN/TIES-verions2/python/models/basic_model.py", line 365, in build_computation_graphs
    vertices_y2, vertices_x2, scale_y, scale_x)
  File "/home/hungdv/Documents/graphNN/TIES-verions2/python/ops/ties.py", line 32, in gather_features_from_conv_head
    return tf.gather_nd(conv_head, indexing_tensor)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 3796, in gather_nd
    return gen_array_ops.gather_nd(params, indices, name=name)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3991, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/home/hungdv/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)

**Comment by GZDXLQH** [comment]
@hxk11111 Hi，I am facing the same problem，it is so strange. Could you tell me how do you solve it ?

**Comment by sankhoroy** [comment]
> @hxk11111 Hi，I am facing the same problem，it is so strange. Could you tell me how do you solve it ?

I also faced same problem. I have rewritten the code and able to solve many issues. I faced the above https://github.com/shahrukhqasim/TIES-2.0/issues/22#issuecomment-560256373 problem when running on my Ununtu (16.04) Machine. In windows machine (Windows 10.x) this problem seems to vanish.

**Comment by kmanojkkmr** [comment]
@hxk11111 ,
I have very bad results for Columns and Cells validation. But getting good result for Rows. Could you please provide your Config.ini file.
Also, are you able to make inference on a single image..? If yes, please let me know how you did it.

Thank you in advance. :)

**Comment by zhaozheninside** [comment]
@hxk11111 
Did you solved this provlem ?  many thanks
