### ISSUE TITLE
"is_sampling_balanced" is required but missing in the example config

### ISSUE THREAD

**Issue by munikarmanish** [shahrukhqasim/TIES-2.0#5]
```
(ties) manish@gpu:~/code/TIES-2.0/python$ python bin/iterate/table_adjacency_parsing.py ../configs/config.ini basic_conv_graph
Traceback (most recent call last):
  File "bin/iterate/table_adjacency_parsing.py", line 31, in <module>
    trainer.train()
  File "/home/manish/code/TIES-2.0/python/iterators/table_adjacency_parsing_iterator.py", line 48, in train
    model.initialize(training=True)
  File "/home/manish/code/TIES-2.0/python/models/basic_model.py", line 51, in initialize
    self.is_sampling_balanced = gconfig.get_config_param("is_sampling_balanced", "bool")
  File "/home/manish/code/TIES-2.0/python/libs/configuration_manager.py", line 34, in get_config_param
    if config_manager_instance.config[key] == "true":
  File "/usr/lib/python3.5/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'is_sampling_balanced'
```

**Comment by dexterslabs** [comment]
adding is_sampling_balanced=True in the config.ini should fix this problem
